### ISSUE TITLE
좌표계 관련 백엔드 개발 이슈

### ISSUE THREAD

**Issue by hyeonprojects** [would-you-study-with-me/siksa-clock#107]
# 현재 문제점 및 해결 논의점 🦅 

### DB에 저장된 X, Y 좌표계 값이 TM 좌표계로 되어 있는데, 나머지 기본 API가 WGS84 좌표계로 되어 있어서 이를 수정해야함
- Kakao API 중에 좌표계 따라서 변환하는 서비스가 있습니다. 이를 사용하기
- 수식을 찾아서 이를 기능으로 구현하기

### 위경도 값이 프론트에서 어떤 좌표계 값으로 가져오게 되는지 궁금함.
- 프론트에서 데이터를 가져와도 이 값이 정확할지 이슈가 있음. 관련해서 프론트와 조사가 필요함

**Comment by hyeonprojects** [comment]
@MaetDol @SoheeP @jihyundev 의견 주시면 감사하겠습니다.

**Comment by hyeonprojects** [comment]
Geolocation 대해서 찾아보니 GPS 기반으로 좌표계를 만든 WGS84을 사용하면 똑같은 좌표값으로 찾아갑니다. 다만 문제점이 DB에 있는 값이 TM 좌표계여서 이를 처리하는 기능을 만들어야할 거 같아요. (여러분들이 보시면 알겁니다. 소수점이 있고 없는 큰 차이가 있어요.)

**Comment by hyeonprojects** [comment]
여담으로 테스트 자바스크립트 코드를 작성해보았는데요.
`navigator.geolocation.getCurrentPosition(success, error, options);`
위 코드에서 처럼 option값으로 정밀도를 올릴 수 있긴 하더라구요. 관련해서 참고하면 좋을거 같습니다.

[예제 코드](https://developer.mozilla.org/ko/docs/Web/API/Geolocation/getCurrentPosition)

**Comment by hyeonprojects** [comment]
##결론

웹 브라우저에 포함된 Javascript 메서드는 GPS를 가져오는데, WGS84 좌표계는 GPS를 기반으로 하기 떄문에 상관없습니다. 다만 데이터베이스에 저장된 x,y은 다른 걸 기반으로 되어 있어서, 이 좌표계를 변환해야 합니다.

## 설명 여지도
지구는 구의 모양으로 표현하지만, 정확히는 완벽한 타원형도 완벽한 구의 모양도 아닙니다.
실제로는 울퉁불퉁한 표면을 가지고 있는데 이를 수학적으로 완벽히 구현하기 힘들기 때, 수학적으로 쉽게 계산하기 위해서 여러학여러 학자가와 유사한 타원체(Geoid)를 만들었습니다.

지구는 똑같은 요철로 튀어나와 있지 않습니다. (당장 산의 높이도 각각 다르고 위치도 대칭이거나 하지 않습니다)
각각의 계산 방법(중력에기원)을 타원체를 채용합니다.
이런 타원체 지오이드라고 합니다. 

우리나라에서는 1841년에 만들어진 Bessel(버셀) 타원체를 사용하여 만든 일제강점기에 만들어진 동경 좌표계를 사용하여서 사용했습니다. 
 
GPS용 세계지도좌표계가 만들어지기 전까지 동경좌표계를 사용합니다. 

이는 타원체 상에서 3차원 좌표이므로 우리가 보는 2차원 지도상의 좌표와는 다르게 됩니다.
곡면과 평면의 차이로써 타원체에서 평면으로 바꾸기 위해서 투영이라는 것을 거칩니다. 투영은 또 여러 지도체계가 분류됩니다.

우리나라에서 사용하는 베셀타원체의 투영법은 TM 도법을 사용합니다.
그래서 베셀타원체를 TM 좌표 또는 TM 도법이라고 합니다.

WGS84 타원체의 경우는 UTM 도법을 사용하여 투영합니다.
UTM도 TM과 같은 방법으로 투영계산을 거치지만 상숫값이 다릅니다.

결론 계산법에서 타원체랑 투영법만 같으면 괜찮습니다.

**Comment by hyeonprojects** [comment]
@SoheeP @jihyundev 좌표계 잘아신다고 봐주신다 했습니다.

**Comment by SoheeP** [comment]
> @SoheeP @jihyundev 좌표계 잘아신다고 봐주신다 했습니다.

무슨소리 하시는지 모르겠습니다 탈주하겠습니다

**Comment by MaetDol** [comment]
`enableHighAccuracy` 옵션이 있군요.. 신기...

proj 라는 라이브러리로 변환 가능한 것 같은데 좀 더 찾아봐야겠네요
수식같은게 있음 좋을 것 가틍데 🤔

**Comment by MaetDol** [comment]
> 결론 계산법에서 타원체랑 투영법만 같으면 괜찮습니다.
고렇다면 상수만 알면 계산할 수 있는걸까요? 👀 

투영원점 가산수치가 60만이라는 말이 있긴 한데..
복잡하네요 좌표계 😢

**Comment by hyeonprojects** [comment]
말해준 대로 proj 라이브러리에 변환이 가능한 거 같더라고요.
제가 찾은건 아니고 @jihyundev 찾아줬는데, 관련해서 변환이 제대로 되는 건가 테스트해볼게요.
좌표계 도메인 지식이 너무 없어서 이걸 어떻게 해야할지 모르겠어요.

**Comment by hyeonprojects** [comment]
DB 데이터 변환을 했는데 데이터에 좌표값이 잘라져서 올라가서 제대로 된 값이 등록되지 않고 있습니다. ㅠㅠ
이 점 확인해서 해결법을 조사해보겠습니다.

**Comment by hyeonprojects** [comment]
DB에 있는 좌표계가 TM 좌표계였고, 이를 변경하는게 여러 작업하는게 좋아보였습니다.
여러분들이 찾아준 라이브러리에 의해서 Proj 라는 라이브러리 중에 pyproj를 @jihyundev 에게 추천 받았습니다.
라이브러리에 다행이 값을 바꾸었고,  epsg:2097(TM) -> epsg:4326(WGS84)로 변경을 하였습니다.

변경을 완료했고, 완벽하게 정밀도가 있기 보다는 2블럭 안에 근처까지 정밀도를 올렸습니다.
이 정도이면 근처 순서부터 뜨게하면 될거 같습니다.
