### ISSUE TITLE
[Feature] Slider 컴포넌트를 만든다

### ISSUE THREAD

**Issue by MaetDol** [would-you-study-with-me/siksa-clock#180]
슬라이더 컴포넌트 작업

한번에 하나의 아이템이 나오는 버전과 여러개가 나오는 버전을 구현한다

**Comment by MaetDol** [comment]
고려해야 할 게 많을 것 같아 모나님이 사용한 slick 을 사용하는걸로,,,

**Comment by hyeonprojects** [comment]
싫어 하드 코딩 해줘.
