### ISSUE TITLE
거리 계산 로직 작성

### ISSUE THREAD

**Issue by jihyundev** [would-you-study-with-me/siksa-clock#89]
유저의 현재 위치와 식당의 x, y좌표를 비교하여 거리를 계산하는 로직을 작성합니다. 
유저의 위치를 얻어오지 못할 경우 UI에 랜더링하지 않습니다.

**Comment by jihyundev** [comment]
https://developer.mozilla.org/ko/docs/Web/API/Geolocation_API/Using_the_Geolocation_API

**Comment by hyeonprojects** [comment]
유저 위치를 못 얻어오는 거에 대해서 고민되네요. 관련해서 논의 해보면 좋을거 같아요. ㅎㅎ

**Comment by hyeonprojects** [comment]
위 Gelocation Javascript API 사용해봤는데, 웹 페이지에 권한 허가랑 기기 환경 따라서 차이가 조금 나는거 같기는 했어요.
나쁘진 않습니다. :)
